name: Psalm Security Scan

on:
  push:
    branches: [ v6.0.x ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ v6.0.x ]

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm Security Scan
        uses: oseki-guy/psalm-github-security-scan@34b38c1c94d873d3d4309d39e9f26356e2c6e8df
        
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
